/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface BatchResult {
  success: boolean
  kind?: string
  format?: string
  width?: number
  height?: number
  colorSpace?: string
  exif?: Record<string, string>
  icc?: Record<string, string>
  duration?: number
  creationTime?: string
  containerCreationTime?: string
  codec?: string
  overallBitrate?: number
  videoBitrate?: number
  frameRate?: number
  metadata?: Record<string, string>
  fileHash?: string
  path?: string
  message?: string
}

export declare function extractMeta(path: string, options?: ExtractOptions | undefined | null): Promise<MediaMeta>

export declare function extractMetaBatch(paths: Array<string>, options?: ExtractOptions | undefined | null): Promise<Array<BatchResult>>

export interface ExtractOptions {
  concurrency?: number
  hash?: boolean
}

export interface MediaMeta {
  kind: string
  format: string
  width: number
  height: number
  colorSpace: string
  exif: Record<string, string>
  icc: Record<string, string>
  duration?: number
  creationTime?: string
  containerCreationTime?: string
  codec?: string
  overallBitrate?: number
  videoBitrate?: number
  frameRate?: number
  metadata: Record<string, string>
  fileHash?: string
}
